"""Student table

Revision ID: 251889351ab3
Revises: 
Create Date: 2026-08-15 11:49:30.728062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251889351ab3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.Text(), nullable=True),
    sa.Column('class_section', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
