"""owner Column

Revision ID: 245091e9cd33
Revises: 482dddf2177d
Create Date: 2026-08-11 09:23:10.754988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245091e9cd33'
down_revision = '482dddf2177d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
